# Get all tutors.

GET http://localhost:9080/simple-ucm/api/tutors

###

# Get single tutor.

GET http://localhost:9080/simple-ucm/api/tutor/3c6f1eb1-8069-44ab-988f-d7fed2b65d87

###

# Get single tutor avatar.

GET http://localhost:9080/simple-ucm/api/tutor/3e35d8f7-f6aa-4a7b-8b44-39a63ed6205f/avatar

###

# Create new tutor.

PUT http://localhost:9080/simple-ucm/api/tutor/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Content-Type: application/json

{
  "name": "Sigrid",
  "dateOfBirth": "2005-05-15",
  "email": "Sigrid@sigrid.com",
  "tutorRank": "PROFESSOR"
}

###

# Create tutor avatar.

PUT http://localhost:9080/simple-ucm/api/tutor/6a0cdff3-dc2d-4bb9-8582-3c7957fb01db/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="klopp-juergen.jpg'

< university-course-manager/src/main/resources/avatar/klopp-juergen.jpg
--boundary--

###

# Update tutor.

PATCH http://localhost:9080/simple-ucm/api/tutor/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Content-Type: application/json

{
  "email": "SirSigrid@Sigrid.com",
  "tutorRank": "LECTURER"
}

###

# Update tutor avatar.

PATCH http://localhost:9080/simple-ucm/api/tutor/3e35d8f7-f6aa-4a7b-8b44-39a63ed6205f/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="klopp-juergen.jpg'

< university-course-manager/src/main/resources/avatar/klopp-juergen.jpg
--boundary--

###

###

# Delete tutor.

DELETE http://localhost:9080/simple-ucm/api/tutor/3c6f1eb1-8069-44ab-988f-d7fed2b65d87

###

# Delete tutor avatar.

DELETE http://localhost:9080/simple-ucm/api/tutor/6a0cdff3-dc2d-4bb9-8582-3c7957fb01db/avatar