# Get all courses.

GET http://localhost:9080/simple-ucm/api/courses

###

# Get single course.

GET http://localhost:9080/simple-ucm/api/courses/cc0b0577-bb6f-45b7-81d6-3db88e6ac19f

###

# Get courses by university.

GET http://localhost:9080/simple-ucm/api/universities/5d1da2ae-6a14-4b6d-8b4f-d117867118d4/courses

###

# Get courses by tutor.

GET http://localhost:9080/simple-ucm/api/tutors/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/courses

###


# Create new course.

PUT http://localhost:9080/simple-ucm/api/courses/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Content-Type: application/json

{
  "name": "Mathematics",
  "description": "An advanced course on Mathematics",
  "studyType": "BACHELOR",
  "passingThreshold": "2.99",
  "semester": "1",
  "tutor": "c4804e0f-769e-4ab9-9ebe-0578fb4f00a6",
  "university": "2d9b1e8c-67c5-4188-a911-5f064a63d8cd"
}

###

# Update course.

PATCH http://localhost:9080/simple-ucm/api/courses/ff327e8a-77c0-4f9b-90a2-89e16895d1e1
Content-Type: application/json

{
  "name": "Law and Economics",
  "description": "An introductory course on Law and Economics",
  "passingThreshold": "2.98"
}

###

# Delete course.

DELETE http://localhost:9080/simple-ucm/api/courses/ff327e8a-77c0-4f9b-90a2-89e16895d1e1
